version: "2"
services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=hvzhvz
      - POSTGRES_USER=hvz

  memcached:
    image: memcached:alpine
    restart: always
    mem_limit: 128M
    # mem_reservation: 64M

  redis:
    image: redis:alpine
    restart: always

  celery:
    build: .
    restart: always
    links:
      - postgres:db
      - redis
      - memcached
    environment:
      - C_FORCE_ROOT=true
    command: "celery worker"

  hvz:
    build: .
    links:
      - postgres:db
      - redis
      - celery
      - memcached
    restart: always
    volumes:
      - ./:/app
    environment:
      - WORKERS=4
    ports:
      - "127.0.0.1:5001:8080"
