version: "2"
services:
  postgres:
    image: postgres:alpine
    volumes:
      - ../hvz_pgdb:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=hvzhvz
      - POSTGRES_USER=hvz

  memcached:
    image: memcached:alpine
    restart: always
    mem_limit: 128M

  redis:
    image: redis:alpine
    restart: always

  celery:
    build: .
    restart: always
    links:
      - postgres:db
      - redis
      - memcached
    volumes:
      - ./:/app
    environment:
      - C_FORCE_ROOT=true
    command: "celery worker -b redis://redis:6379/3 --app uchicagohvz.celery_app"

  hvz:
    build: .
    links:
      - postgres:db
      - redis
      - celery
      - memcached
    restart: always
    volumes:
      - ./:/app
    environment:
      - WORKERS=4
    ports:
      - "127.0.0.1:5001:8080"

  chat:
    build: .
    restart: always
    ports:
      - "127.0.0.1:36452:36452"
    volumes:
      - ./:/app
    command: "node uchicagohvz/chat/server/server.js"
