version: "2"
services:
  postgres:
    image: postgres:alpine
    volumes:
      - ../hvz_pgdb:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=hvzhvz
      - POSTGRES_USER=hvz

  memcached:
    image: memcached:alpine
    restart: always
    mem_limit: 128M
    # mem_reservation: 64M

  redis:
    image: redis:alpine
    restart: always

  celery:
    build: .
    restart: always
    links:
      - postgres:db
      - redis
      - memcached
    environment:
      - C_FORCE_ROOT=true
      - CELERY_APP=uchicagohvz.celery_app
      - BROKER_URL=redis://redis:6379/3
    command: "celery worker -b $BROKER_URL --app $CELERY_APP"

  hvz:
    build: .
    links:
      - postgres:db
      - redis
      - celery
      - memcached
    restart: always
    environment:
      - WORKERS=4
    ports:
      - "127.0.0.1:5001:8080"
